// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.simian.game.server.proto;

public final class MessageRequestProto {
  private MessageRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 method = 1;
    /**
     * <code>optional int32 method = 1;</code>
     *
     * <pre>
     *要执行的命令的方法
     * </pre>
     */
    boolean hasMethod();
    /**
     * <code>optional int32 method = 1;</code>
     *
     * <pre>
     *要执行的命令的方法
     * </pre>
     */
    int getMethod();

    // optional int32 model = 2;
    /**
     * <code>optional int32 model = 2;</code>
     *
     * <pre>
     *要执行的命令的类
     * </pre>
     */
    boolean hasModel();
    /**
     * <code>optional int32 model = 2;</code>
     *
     * <pre>
     *要执行的命令的类
     * </pre>
     */
    int getModel();

    // optional string sessionId = 3;
    /**
     * <code>optional string sessionId = 3;</code>
     */
    boolean hasSessionId();
    /**
     * <code>optional string sessionId = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // optional string sn = 4;
    /**
     * <code>optional string sn = 4;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    boolean hasSn();
    /**
     * <code>optional string sn = 4;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    java.lang.String getSn();
    /**
     * <code>optional string sn = 4;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    // optional string dataType = 5;
    /**
     * <code>optional string dataType = 5;</code>
     */
    boolean hasDataType();
    /**
     * <code>optional string dataType = 5;</code>
     */
    java.lang.String getDataType();
    /**
     * <code>optional string dataType = 5;</code>
     */
    com.google.protobuf.ByteString
        getDataTypeBytes();

    // optional bytes value = 6;
    /**
     * <code>optional bytes value = 6;</code>
     */
    boolean hasValue();
    /**
     * <code>optional bytes value = 6;</code>
     */
    com.google.protobuf.ByteString getValue();

    // optional int32 zip = 7;
    /**
     * <code>optional int32 zip = 7;</code>
     *
     * <pre>
     *是否压缩 value
     * </pre>
     */
    boolean hasZip();
    /**
     * <code>optional int32 zip = 7;</code>
     *
     * <pre>
     *是否压缩 value
     * </pre>
     */
    int getZip();

    // optional int64 token = 8;
    /**
     * <code>optional int64 token = 8;</code>
     */
    boolean hasToken();
    /**
     * <code>optional int64 token = 8;</code>
     */
    long getToken();
  }
  /**
   * Protobuf type {@code MessageRequest}
   */
  public static final class MessageRequest extends
      com.google.protobuf.GeneratedMessage
      implements MessageRequestOrBuilder {
    // Use MessageRequest.newBuilder() to construct.
    private MessageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageRequest defaultInstance;
    public static MessageRequest getDefaultInstance() {
      return defaultInstance;
    }

    public MessageRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              method_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              model_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessionId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              sn_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              dataType_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              value_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              zip_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              token_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.simian.game.server.proto.MessageRequestProto.internal_static_MessageRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.simian.game.server.proto.MessageRequestProto.internal_static_MessageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.simian.game.server.proto.MessageRequestProto.MessageRequest.class, com.simian.game.server.proto.MessageRequestProto.MessageRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageRequest> PARSER =
        new com.google.protobuf.AbstractParser<MessageRequest>() {
      public MessageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 method = 1;
    public static final int METHOD_FIELD_NUMBER = 1;
    private int method_;
    /**
     * <code>optional int32 method = 1;</code>
     *
     * <pre>
     *要执行的命令的方法
     * </pre>
     */
    public boolean hasMethod() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 method = 1;</code>
     *
     * <pre>
     *要执行的命令的方法
     * </pre>
     */
    public int getMethod() {
      return method_;
    }

    // optional int32 model = 2;
    public static final int MODEL_FIELD_NUMBER = 2;
    private int model_;
    /**
     * <code>optional int32 model = 2;</code>
     *
     * <pre>
     *要执行的命令的类
     * </pre>
     */
    public boolean hasModel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 model = 2;</code>
     *
     * <pre>
     *要执行的命令的类
     * </pre>
     */
    public int getModel() {
      return model_;
    }

    // optional string sessionId = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private java.lang.Object sessionId_;
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sn = 4;
    public static final int SN_FIELD_NUMBER = 4;
    private java.lang.Object sn_;
    /**
     * <code>optional string sn = 4;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sn = 4;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    public java.lang.String getSn() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sn = 4;</code>
     *
     * <pre>
     *序号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      java.lang.Object ref = sn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string dataType = 5;
    public static final int DATATYPE_FIELD_NUMBER = 5;
    private java.lang.Object dataType_;
    /**
     * <code>optional string dataType = 5;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string dataType = 5;</code>
     */
    public java.lang.String getDataType() {
      java.lang.Object ref = dataType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dataType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      java.lang.Object ref = dataType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes value = 6;
    public static final int VALUE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>optional bytes value = 6;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes value = 6;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    // optional int32 zip = 7;
    public static final int ZIP_FIELD_NUMBER = 7;
    private int zip_;
    /**
     * <code>optional int32 zip = 7;</code>
     *
     * <pre>
     *是否压缩 value
     * </pre>
     */
    public boolean hasZip() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 zip = 7;</code>
     *
     * <pre>
     *是否压缩 value
     * </pre>
     */
    public int getZip() {
      return zip_;
    }

    // optional int64 token = 8;
    public static final int TOKEN_FIELD_NUMBER = 8;
    private long token_;
    /**
     * <code>optional int64 token = 8;</code>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 token = 8;</code>
     */
    public long getToken() {
      return token_;
    }

    private void initFields() {
      method_ = 0;
      model_ = 0;
      sessionId_ = "";
      sn_ = "";
      dataType_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      zip_ = 0;
      token_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, method_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, model_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSnBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getDataTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, value_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, zip_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(8, token_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, method_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, model_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSnBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDataTypeBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, value_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, zip_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, token_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.simian.game.server.proto.MessageRequestProto.MessageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.simian.game.server.proto.MessageRequestProto.MessageRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.simian.game.server.proto.MessageRequestProto.MessageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.simian.game.server.proto.MessageRequestProto.internal_static_MessageRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.simian.game.server.proto.MessageRequestProto.internal_static_MessageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.simian.game.server.proto.MessageRequestProto.MessageRequest.class, com.simian.game.server.proto.MessageRequestProto.MessageRequest.Builder.class);
      }

      // Construct using com.simian.game.server.proto.MessageRequestProto.MessageRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        method_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        model_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sn_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        dataType_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        zip_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        token_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.simian.game.server.proto.MessageRequestProto.internal_static_MessageRequest_descriptor;
      }

      public com.simian.game.server.proto.MessageRequestProto.MessageRequest getDefaultInstanceForType() {
        return com.simian.game.server.proto.MessageRequestProto.MessageRequest.getDefaultInstance();
      }

      public com.simian.game.server.proto.MessageRequestProto.MessageRequest build() {
        com.simian.game.server.proto.MessageRequestProto.MessageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.simian.game.server.proto.MessageRequestProto.MessageRequest buildPartial() {
        com.simian.game.server.proto.MessageRequestProto.MessageRequest result = new com.simian.game.server.proto.MessageRequestProto.MessageRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.method_ = method_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.dataType_ = dataType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.zip_ = zip_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.token_ = token_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.simian.game.server.proto.MessageRequestProto.MessageRequest) {
          return mergeFrom((com.simian.game.server.proto.MessageRequestProto.MessageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.simian.game.server.proto.MessageRequestProto.MessageRequest other) {
        if (other == com.simian.game.server.proto.MessageRequestProto.MessageRequest.getDefaultInstance()) return this;
        if (other.hasMethod()) {
          setMethod(other.getMethod());
        }
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000004;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasSn()) {
          bitField0_ |= 0x00000008;
          sn_ = other.sn_;
          onChanged();
        }
        if (other.hasDataType()) {
          bitField0_ |= 0x00000010;
          dataType_ = other.dataType_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasZip()) {
          setZip(other.getZip());
        }
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.simian.game.server.proto.MessageRequestProto.MessageRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.simian.game.server.proto.MessageRequestProto.MessageRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 method = 1;
      private int method_ ;
      /**
       * <code>optional int32 method = 1;</code>
       *
       * <pre>
       *要执行的命令的方法
       * </pre>
       */
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 method = 1;</code>
       *
       * <pre>
       *要执行的命令的方法
       * </pre>
       */
      public int getMethod() {
        return method_;
      }
      /**
       * <code>optional int32 method = 1;</code>
       *
       * <pre>
       *要执行的命令的方法
       * </pre>
       */
      public Builder setMethod(int value) {
        bitField0_ |= 0x00000001;
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 method = 1;</code>
       *
       * <pre>
       *要执行的命令的方法
       * </pre>
       */
      public Builder clearMethod() {
        bitField0_ = (bitField0_ & ~0x00000001);
        method_ = 0;
        onChanged();
        return this;
      }

      // optional int32 model = 2;
      private int model_ ;
      /**
       * <code>optional int32 model = 2;</code>
       *
       * <pre>
       *要执行的命令的类
       * </pre>
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 model = 2;</code>
       *
       * <pre>
       *要执行的命令的类
       * </pre>
       */
      public int getModel() {
        return model_;
      }
      /**
       * <code>optional int32 model = 2;</code>
       *
       * <pre>
       *要执行的命令的类
       * </pre>
       */
      public Builder setModel(int value) {
        bitField0_ |= 0x00000002;
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 model = 2;</code>
       *
       * <pre>
       *要执行的命令的类
       * </pre>
       */
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        model_ = 0;
        onChanged();
        return this;
      }

      // optional string sessionId = 3;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // optional string sn = 4;
      private java.lang.Object sn_ = "";
      /**
       * <code>optional string sn = 4;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string sn = 4;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public java.lang.String getSn() {
        java.lang.Object ref = sn_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sn = 4;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        java.lang.Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sn = 4;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public Builder setSn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sn = 4;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sn = 4;</code>
       *
       * <pre>
       *序号
       * </pre>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sn_ = value;
        onChanged();
        return this;
      }

      // optional string dataType = 5;
      private java.lang.Object dataType_ = "";
      /**
       * <code>optional string dataType = 5;</code>
       */
      public boolean hasDataType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string dataType = 5;</code>
       */
      public java.lang.String getDataType() {
        java.lang.Object ref = dataType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dataType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dataType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getDataTypeBytes() {
        java.lang.Object ref = dataType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dataType = 5;</code>
       */
      public Builder setDataType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataType = 5;</code>
       */
      public Builder clearDataType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dataType_ = getDefaultInstance().getDataType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dataType = 5;</code>
       */
      public Builder setDataTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        dataType_ = value;
        onChanged();
        return this;
      }

      // optional bytes value = 6;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes value = 6;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes value = 6;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>optional bytes value = 6;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes value = 6;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      // optional int32 zip = 7;
      private int zip_ ;
      /**
       * <code>optional int32 zip = 7;</code>
       *
       * <pre>
       *是否压缩 value
       * </pre>
       */
      public boolean hasZip() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 zip = 7;</code>
       *
       * <pre>
       *是否压缩 value
       * </pre>
       */
      public int getZip() {
        return zip_;
      }
      /**
       * <code>optional int32 zip = 7;</code>
       *
       * <pre>
       *是否压缩 value
       * </pre>
       */
      public Builder setZip(int value) {
        bitField0_ |= 0x00000040;
        zip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 zip = 7;</code>
       *
       * <pre>
       *是否压缩 value
       * </pre>
       */
      public Builder clearZip() {
        bitField0_ = (bitField0_ & ~0x00000040);
        zip_ = 0;
        onChanged();
        return this;
      }

      // optional int64 token = 8;
      private long token_ ;
      /**
       * <code>optional int64 token = 8;</code>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 token = 8;</code>
       */
      public long getToken() {
        return token_;
      }
      /**
       * <code>optional int64 token = 8;</code>
       */
      public Builder setToken(long value) {
        bitField0_ |= 0x00000080;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 token = 8;</code>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000080);
        token_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MessageRequest)
    }

    static {
      defaultInstance = new MessageRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MessageRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\"\213\001\n\016MessageRequest\022\016\n\006me" +
      "thod\030\001 \001(\005\022\r\n\005model\030\002 \001(\005\022\021\n\tsessionId\030\003" +
      " \001(\t\022\n\n\002sn\030\004 \001(\t\022\020\n\010dataType\030\005 \001(\t\022\r\n\005va" +
      "lue\030\006 \001(\014\022\013\n\003zip\030\007 \001(\005\022\r\n\005token\030\010 \001(\003B3\n" +
      "\034com.simian.game.server.protoB\023MessageRe" +
      "questProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MessageRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MessageRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageRequest_descriptor,
              new java.lang.String[] { "Method", "Model", "SessionId", "Sn", "DataType", "Value", "Zip", "Token", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
